# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86c61ef7e679026cb5a731431fcfe19a862f9d61bb05ff355a201054136bd550444ea1604b8934945d1a3c9e55a2632cecbfb4261d00c4d2f8d8f9cc31ff655b

test:
  secret_key_base: 1854622723fe109ed19cc6975036204626a09a7227dd4799321f68847f491a1293235ea4a0027ed3dd99f07b8d441c355bdb6c97ee4277dbd58b527670b55bcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
